#!/usr/bin/env python
import psycopg2
from psycopg2.extras import DictCursor
from sys import argv
from textwrap import dedent


def get_connection(dbname):
    """Gets a connection to the given database"""
    return psycopg2.connect(dbname=dbname)


def get_cursor(db_connection):
    """Gets a cursor to the given db_connection"""
    return db_connection.cursor(cursor_factory=DictCursor)


def execute_select_query(db_cursor, query):
    """executes a select SQL query  using the given db_cursor"""
    cursor.execute(query)
    return db_cursor.fetchall()


def list_expenses(db_cursor):
    """Prints all expenses in a | delminted table"""
    query = "SELECT * FROM expenses"
    expenses = execute_select_query(cursor, query)

    for expense in expenses:
        print(
            f"{expense['id']} | {expense['created_on']} | "
            f"{expense['amount']:>12} | {expense['memo']}"
        )


def display_help():
    print(dedent("""
        An expense recording system

        Commands:

        add AMOUNT MEMO - record a new expense
        clear - delete all expenses
        list - list all expenses
        delete NUMBER - remove expense with id NUMBER
        search QUERY - list expenses with a matching memo field
    """))


if __name__ == "__main__":
    try:
        connection = get_connection(dbname="expense")
        cursor = get_cursor(connection)

        if argv[0]:
            match argv[1].lower():
                case "list":
                    list_expenses(cursor)
                case "help":
                    display_help()
    finally:
        connection.close()
